<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-UUTKFR9P" ignored="0" name="test1" tests="7" failures="3" timestamp="2020-11-11T10:52:15 CST" time="18.195" errors="0">
  <testcase name="@AfterClass doAfterMethod" time="0.055" classname="com.webtest.core.BaseTest">
    <failure type="org.openqa.selenium.NoSuchSessionException" message="Tried to run command without establishing a connection
Build info: version: &amp;apos;3.141.59&amp;apos;, revision: &amp;apos;e82be7d358&amp;apos;, time: &amp;apos;2018-11-14T08:25:53&amp;apos;
System info: host: &amp;apos;LAPTOP-UUTKFR9P&amp;apos;, ip: &amp;apos;192.168.137.1&amp;apos;, os.name: &amp;apos;Windows 10&amp;apos;, os.arch: &amp;apos;amd64&amp;apos;, os.version: &amp;apos;10.0&amp;apos;, java.version: &amp;apos;1.8.0_171&amp;apos;
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 82.0.1, javascriptEnabled: true, moz:accessibilityChecks: false, moz:buildID: 20201026153733, moz:geckodriverVersion: 0.24.0, moz:headless: false, moz:processID: 9640, moz:profile: C:\Users\lenovo\AppData\Loc..., moz:shutdownTimeout: 60000, moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, platformVersion: 10.0, rotatable: false, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}
Session ID: afa06e96-3e9a-47e2-a488-05cc1ac38c3e">
      <![CDATA[org.openqa.selenium.NoSuchSessionException: Tried to run command without establishing a connection
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'LAPTOP-UUTKFR9P', ip: '192.168.137.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_171'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 82.0.1, javascriptEnabled: true, moz:accessibilityChecks: false, moz:buildID: 20201026153733, moz:geckodriverVersion: 0.24.0, moz:headless: false, moz:processID: 9640, moz:profile: C:\Users\lenovo\AppData\Loc..., moz:shutdownTimeout: 60000, moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, platformVersion: 10.0, rotatable: false, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}
Session ID: afa06e96-3e9a-47e2-a488-05cc1ac38c3e
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:609)
at org.openqa.selenium.remote.RemoteWebDriver.quit(RemoteWebDriver.java:452)
at com.webtest.core.BaseTest.doAfterMethod(BaseTest.java:95)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- @AfterClass doAfterMethod -->
  <testcase name="demo1" time="0.007" classname="com.webtest.demo.Admin_Login">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
at com.webtest.demo.Admin_Login.demo1(Admin_Login.java:30)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- demo1 -->
  <testcase name="demo2" time="0.002" classname="com.webtest.demo.Admin_Login"/>
  <testcase name="demo3" time="0.001" classname="com.webtest.demo.Admin_Login"/>
  <testcase name="demo4" time="0.001" classname="com.webtest.demo.Admin_Login">
    <failure type="java.lang.AssertionError" message="expected [2] but found [3]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [3]
at com.webtest.demo.Admin_Login.demo4(Admin_Login.java:42)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- demo4 -->
  <testcase name="demo5" time="0.002" classname="com.webtest.demo.Admin_Login"/>
  <testcase name="demo6" time="0.001" classname="com.webtest.demo.Admin_Login">
    <failure type="java.lang.AssertionError" message="expected [4] but found [7]">
      <![CDATA[java.lang.AssertionError: expected [4] but found [7]
at com.webtest.demo.Admin_Login.demo6(Admin_Login.java:50)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- demo6 -->
  <testcase name="testLogin" time="9.061" classname="com.webtest.demo.Admin_Login"/>
</testsuite> <!-- test1 -->
